language: go
go:
- 1.8
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKER_EMAIL=fbgrecojr@me.com
  - DOCKER_USER=fbgrecojr
  - secure: d3mkRKUM+nYNM9MSFb2zFH8DB0Jva9c1HVL7J76kW3k63wZarU0U/+Z/H6U3gebxK/UgfmThcKnT+bhFXxfWfBTntYhfM5OWYTgCFFw5cxfcyBbKjfytsz403R9gNr7VBfNqYIImWSRmcpS11V1VVTbt5EcfKLnxjP4fvOIVyG+0l8PFFUphWmNr848KCH+0c9ZxwnvCAsMmP7N6puxmyFkF6IEoje8x0T4Cb0ci/6M2+pBdXO0aUldHZcZmgPzOD3ATn6qcHv7md1RHhp6hPkwnVZdKW83HfgHU2qmiS/MRJjhPfhYmTjz2KREf9Z9W6OGn99xIzL5H2lum0YnEsqqiQJPJr0QndwIUjbx9QTRyKkS18CMQ/fwOTQsAlaY/7ipYgfZ+CoWUXEfk6gSw1aoVkgHi0M19rl2gWbU0uaQsnxlh7B8u7BMnoeq0KVghaYLHR1ALTmuH88a+5VrZCFAmaBr/WvO/0TN7TzQrXwy5+6fSvM7NwiDVRBq/UjuUVRgx2QbQHFecQlGJCYbsH7owS+uWbgIVZwlP0ZzvkHZhp9NgXm5NIGRZFNbsFS3ZgyBancSNvQCkVEGG+lMSqy442+DMdFvjB/w8epyjDvrLfYyPjVw0yOolCZLkny9omuiyDNAIB+2ohgC58A+o8o1N54jEGmP/t0W2ghf0buA=
  - secure: LXE/AnJPeCtB72xeJa/qKxN3Yql3V3i2UhXBoMy/UY6+ouMtxjBVbgE7I5P/jeazB/Z3ek0Hqw9QOVJtqEzSgosCesY4H2ZJmpVGykEjJBEX4PuGwLQWbOe7Wj6dveXVkgucnD81kXhNFdnEwqBe/FCyZC+kYo4Pu4gOafedNRzZz4cZL5Wk7YmseoqsM5GoPNCwwbi46L27OphoY2t8TyFqETp2cjAImq2Zgio723L0V8zmtt6W2oz7M9+7JdwDGdjN2s5W/vBDh7alxb/KGC2j0G/lex3tuBAxL1Q1KSQ61edRp2mNe3LV/8ToB7VeFnEfw5RwUl8YM+L04SZV40nSCNYH7DDg4MnCcbsLDnEJ6TkbMDQ740FhUMA4Dl8xxFDYcWUqlTWPSvDQRZGS9cblWxmNmKwix0V6p+crRt6dbt2uBvPEM61GZj3PovxPhaEMqQMf73ISMUv9NsqABrOt9eYMjCg/e1SFMZBmiH351Z0tH0CNBOzZvVOCUm1hrw3zKfzqQYV/ogCpdB6W2rlqMPNYEVNOz/P6/vJnE9EuoKVb4thPX86nqHaBs/EVMXQm8d8/xagNUuxeDck2Mru1/9zInOMYsaM0SXAzB8OnGhxrvViktKqhDNOT6czpeUzkLnR30FarEb1BhJedVrccjQLd43oajWi+zDATswg=
script:
- cd ~/build/frankgreco/kubenforce && make
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- cd ~/build/frankgreco/kubenforce && docker build -f Dockerfile -t fbgrecojr/kubenforce:latest:$COMMIT
  .
- docker tag fbgrecojr/kubenforce:latest:$COMMIT fbgrecojr/kubenforce:latest:$TAG
- docker push fbgrecojr/kubenforce
