language: go
go:
- 1.8
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKER_EMAIL=fbgrecojr@me.com
  - DOCKER_USER=fbgrecojr
  - secure: GViH2G88tlyAWQokVbIfKc6WtaKISP3HeXJCQV7diFTWlN3EjWFoAKKyscATGsm3t0os9vc5x/hIRKN2oQg9u6ttU/S9lVhrN7qgl742uT1y/CDFkwuXZFbLw2PwLidjsfqoR7p6J7HBBJKsZiSwEmApWkn4yuYXWS8kTtR2RC9ixONx3GZXKkzFnxnfew4vmCguPHcgrStYCOdtaHDIPIkPrX+OGIY4vPzV499Sl/J6xJHTYpHCHCwXZ9zy8lJJaOeio9I0RxDvhqTuIi6yxViql861MK+F4hDor3Umy2wqWhCKzvOWz/iPXVnT78GjxzgiRazb2UstejXDF+iQYDDyMa2jeleCvscQD64Zzto+UFQaeRhTSNWGLGsDBZO6JhY0cIWI1XBFhMeXylntWQGRcg92NfU31CKMjJ95wm3eMOkmIOH63NeXyKMExut0L/Uj0AW7pXVa1GKcfYwDqssAX5V4rxWRe9lK2+c1BYnYaqFRLN5l7ppOe3tgJxQqmpAsESZiVpRZUsUkUNs9JXyPetoNXN2mC7qkw6DxshCI4NfG4otITkNmvcy4yQq7vvsIyxhptN7n+0HVw8xlflBw0ZmmlQsfm94wxzh60wPaI2ilZLL0IfaV1fiFpsBUsTHE+ID98J891faLGLKMjJksks17J4EE0xQtvWVNwSo=
script:
- cd ~/build/frankgreco/kubenforce && make
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- cd ~/build/frankgreco/kubenforce && docker build -f Dockerfile -t fbgrecojr/kubenforce:$COMMIT
  .
- docker tag fbgrecojr/kubenforce:$COMMIT fbgrecojr/kubenforce:$TAG
- docker push fbgrecojr/kubenforce
