language: go

go:
  - 1.8

sudo: required

services:
  - docker

env:
  global:
    - secure: "BsfBcR8JVeWYwdYtk6Wia3tgEjoc8b/4cr0gnsKIoyR3f6FdmAPNrY+ai/49NdsZMvPShBm0ToJxiP1fZEuQ7Ol9OfgcA7bU96kq7eQyT48yrPtx6X/SCStIWVUW6qMjHd8psVh4aRtZegY89cyJgFinMEaePRb3+O7skMxbT2B1WigkRMzWEC2H6o3tGrrEKcGx25/wMzOEOR2rZXW07qMqtnj8ZyG4y3MCNJWu968nN7DUm2TXTMcKIpiTAi4jgm6z5/7UTXhakOQFAQsrcw4tmxy46s4cdoimE4KUJ8vMl+zNXAMacJHYc475AXJjQMxhmZWaWql0oJYbOvSQdQONGAxitHui8cKhDTaPw1LiOW06NQmtK2vdG3ZTMv/V+Ma6IVGbNgrkvsDTFqielcjEYabRJ7oA/5g3jPHv0hrIecJk7aTqoALQ5bDi3UdzfJ0Mpu6FZx4Mnj2FnY7T7/gg7msIVRusSskrGzEAnO1vdcE1ezUxCHM8rY4Rdp/nSLhGvRDbDm6flmARX/xyzvISYlYwDlQxTnjzJyGElJk8BW+3gOY5ArrYw+z0aMjcvaI3mrSkHenZH2yVW6zH2YLcoaafl7JobIkgO+Eoam8zGCVm/7K79XGsyLO3ELETHab8+Xj/QRBNN4/ZHHZPHiGD5RgIjgPZu+S+1RBbNYc="
    - secure: "Dq0Ei7VZWVfXCOUjeVIDaAtDmj5c3QbEYbS15JgVFHPzK4MxcJTklF2gH2E+cwn29tlUi+ZiVrIPayOer8ULXD6GgWpVFtxKwnZXCb2LL0GiO9omM3Pam/P04qbueWOB2bpJ3hfIZiQLa/UWBqIC+3YVHPFB7oUwpNOoT353VW3gvYMMCCW6QT2+NcvefXuMST4M8OKord79E7M/CLdjNT8yx2F2zTmLJRoqtB+FMpDsuY+3W3QQRC0Nx0qxq6xRYrCpUjFa/hqWMAzW4D73XNqz/T0m2iR0XL02FYjjuOBccN02m8ZFmv4jtmuSvHxEkDsYPrLy+2Nb+HBq3mGq+t9h4DajRVE+yWaqKkurR9bAWvhXtZL98ncgZ4gPJnRzwsP5CDTlq4SsXBIWW1QRfMoWT9WuIAGVxvdGWBcy1GyjRlbkpIUAYD9Egvky2c/y9eeDw5TwuUDdHQGAFOfE4QT4OhMYs+UTJ8dL7Q7JmZgmm2Rk3K3fQ/OvO39zlcY0OS54NqnIsxuyyZEUoFEqDX1yvOCexFds4y1fkZv+zhI+OxD2YliwjP4qFUqa4RR8LKt/+CNOED1VMOdlZuYvzOxFGn1yzBPqPP06hXe2krSuvQO5Vrba9e1KcH+3N06myvDN7m8UOOoBflNaVd/XtRfO6NMzMvc8yQfd2L32RE8="
    - secure: "gTkOus8ut7vYyPGyDp5msOflyaAuxm86JF1/O2fcXTTAiMD00R9hFVv4e40oPP0zBswtmFFHLuSta50iRu5cgYFb9c7mR2bIbWw2uwbvrp3Jro+pWT9AFQofxUS+GKokJBlt4P/LcNpb6w2nWEMZ7SqaOJqvMcwtwVMQACSZcebU/6ee7egB5Y1zwsg012ZUXFXYSb+GZh6lpiOxBLCn2BNkzMnzCxcxLI51K0xbc0KaD+3ohEO1Nw7XJmar9bnQKuE/fUsMSaNyTkXXaqNSxshvCRK+sLNvYRk7PuMB0n/gl9w4hBPQmcW6jpZOuyqE1p0olfnruJrNoJCf8f+1UKdcEvi/K9UtwWXneM/HjKv6MHwZdVABCwUX+k4azEt9EV7LfC5eXDg+tagwibZEWA9uF6W2QF+gS3WdulGPuHf27pLVxhu4BR42eubnlhC2yfTFQDQolxYe/wIho/HnQZCRscBinalk+dXQYdbUXM+ZrF+O5gS9PTknKtysuZVznXMn8YmCSWTuRA+Sj6BPZ1d4I+BWq0RZL2oywMFsTRguId+4889U0rkppBu4ZU+jYeviDygOvsTp9iQAnUcVFQMJ6+4kkZtpKO/XvV+OIEgLHkMPThiov9rg61FAlSGqA76ObwNZsEnGrfLHXhtVQxFTa35TV+S+auVGt8/zJr8="
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - cd ~/build/frankgreco/kubenforce && make

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - cd ~/build/frankgreco/kubenforce && docker build -f Dockerfile -t fbgrecojr/kubenforce:latest:$COMMIT .
  - docker tag fbgrecojr/kubenforce:latest:$COMMIT fbgrecojr/kubenforce:latest:$TAG
  - docker push fbgrecojr/kubenforce
