---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-audit
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: k8s-audit
    spec:
      containers:
      - name: k8s-audit
        image: registry.gitlab.com/nm-kubernetes/k8s-audit
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        env:
        - key: ACCESS_TOKEN
          value: 3388a9e50b8ebd590a896d21eb4bc4b338e5c2c9
