---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example
  name: example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: example
  template:
    metadata:
      labels:
        k8s-app: example
    spec:
      containers:
      - name: hello-world
        imagePullPolicy: Always
        image: fbgrecojr/helloworld:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: default
  labels:
    app: example
  annotations:
    source: "https://github.com/frankgreco/k8s-config-policy"
spec:
  selector:
    k8s-app: example
  ports:
  - name: application-port
    port: 8080
    nodePort: 30002
  type: NodePort
