---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-policy
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: config-policy
    spec:
      containers:
      - name: config-policy
        image: fbgrecojr/kubenforce:latest
        imagePullPolicy: Always
