---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example1
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        source: frankgreco
    spec:
      hostNetwork: true
      containers:
      - name: hello-world
        imagePullPolicy: IfNotPresent
        image: fbgrecojr/helloworld:latest
        ports:
        - containerPort: 8080
